language: php

php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm

branches:
    only: master

env:
    global:
        - COMPOSER_PREFER_LOWEST=false
        - SYMFONY_DEPRECATIONS_HELPER=strict

install:
    - if [[ "$TRAVIS_PHP_VERSION" == "5.3.3" ]]; then composer config -g secure-http false; fi
    - if [[ "$TRAVIS_PHP_VERSION" == "5.3.3" ]]; then composer config -g disable-tls true; fi
    - composer self-update
    - composer update --prefer-source `if [[ $COMPOSER_PREFER_LOWEST = true ]]; then echo "--prefer-lowest --prefer-stable"; fi`

script: vendor/bin/phpunit --coverage-clover build/clover.xml

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml

matrix:
    include:
        - php: 5.6
          env: COMPOSER_PREFER_LOWEST=true

notifications:
    email: geloen.eric@gmail.com
